name: Build lambdas
on:
  pull_request:
    branches:
      - main
    paths:
      - 'lambdas/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    container:
      image: node:${{ matrix.node }}
    defaults:
      run:
        working-directory: ./lambdas

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run prettier
        run: yarn format-check
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build distribution
        run: yarn build
