name: Update docs
on:
  push:
    paths:
      - "*.tf"
      - "*.md"
      - ".github/workflows/update-docs.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    # update docs after merge back to develop
    name: Auto update terraform docs
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push'
        name: Checkout branch
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # ratchet:terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: .
          git-commit-message: "docs: auto update terraform docs"
          git-push: ${{ github.ref != 'refs/heads/main' }}

      - name: Create Pull Request (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666 # ratchet:peter-evans/create-pull-request@v5.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Terraform docs"
          title: "docs: Update Terraform docs"
          branch: ${{ github.event.pull_request.base.ref }}-update-docs
          base: ${{ github.event.pull_request.base.ref }}
